PRISM/Controllers/SettingsController.cs
using PRISM.Filters;
using PRISM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PRISM.Controllers
{

    [Authorize]
    [SessionExpireFilter]
    [OutputCacheAttribute(VaryByParam = "*", Duration = 0, NoStore = true)]
    public class SettingsController : PrismBaseController
    {
        private NepalPoliceInventoryEntities db = new NepalPoliceInventoryEntities();
        //
        // GET: /Settings/

        public ActionResult Index()
        {
            return View();
        }

        [SessionExpireFilter]
        public PartialViewResult VendorSetup()
        {

            return PartialView("iVendorSetup");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpireFilter]
        public ActionResult AddVendor(TBL_VENDOR vnd)
        {
            vnd.PK_VENDORID = Guid.NewGuid().ToString();
            vnd.BLOCKED = 0;
            try
            {
                db.TBL_VENDOR.Add(vnd);
                db.SaveChanges();
                return View("Index");

            }
            catch (System.Data.Entity.Validation.DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                            ve.PropertyName, ve.ErrorMessage);
                    }
                }
                return View();

            }
            catch (Exception e)
            {

                var ex = e;
                return View();
            }
        }

        [SessionExpireFilter]
        public ActionResult ViewVendor()
        {
            var dat = new SettingsDbHelper();
            var data = dat.getVendorDetail();
            return PartialView("iViewVendor", data);
        }

        [SessionExpireFilter]
        public ActionResult DetailVendor(string id)
        {
            var qid = id;
            var data = (from x in db.TBL_VENDOR
                        where x.PK_VENDORID == qid
                        select new
                        {
                            x.VENDORNAME,
                            x.ADDRESS,
                            x.ADDRESS2,
                            x.CONTACTPERSON,
                            x.PHONENO,
                            x.PHONENO1,
                            x.EMAIL,
                            x.FAXNO,
                            x.TERRETORY,
                            x.COUNTRY,
                            x.CURRENCYCODE,
                            x.VATREGNO,
                            x.BLOCKED

                        }).AsEnumerable().Select(xs => new PRISM.Models.spVendor
                        {
                            VendorName = xs.VENDORNAME,
                            Address = (xs.ADDRESS == null ? "" : xs.ADDRESS),
                            Address2 = (xs.ADDRESS2 == null ? "" : xs.ADDRESS2),
                            ContactPerson = (xs.CONTACTPERSON == null ? "" : xs.CONTACTPERSON),
                            PhoneNo = (xs.PHONENO == null ? "" : xs.PHONENO),
                            PhoneNo1 = (xs.PHONENO1 == null ? "" : xs.PHONENO1),
                            Email = (xs.EMAIL == null ? "" : xs.EMAIL),
                            FaxNo = (xs.FAXNO == null ? "" : xs.FAXNO),
                            Terretory = (xs.TERRETORY == null ? "" : xs.TERRETORY),
                            Country = (xs.COUNTRY == null ? "" : xs.COUNTRY),
                            CurrencyCod = (xs.CURRENCYCODE == null ? "" : xs.CURRENCYCODE),
                            VatRegistrationNo = (xs.VATREGNO == null ? "" : xs.VATREGNO),
                            isActice = (xs.BLOCKED == 0 ? "Yes" : "No")
                        });
            var rdata = data.SingleOrDefault();
            return PartialView("iVendorDetail", rdata);
        }

        [SessionExpireFilter]
        public ActionResult ConsumptionPeriod()
        {
            var query = (from a in db.TBL_ASSET
                         join b in db.TBL_CONSUMPTION_PERIOD on new { guid = a.PK_ASSET_ID } equals new { guid = b.FK_ITEMID } into b_join
                         from b in b_join.DefaultIfEmpty()
                         where
                           b.FK_ITEMID == null
                         select new
                         {
                             a.ITEMNAME,
                             guid = a.PK_ASSET_ID
                         }).ToList();
            ViewBag.ConsumptionItem = new SelectList(query, "guid", "ITEMNAME");
            ViewBag.TimeFrams = new SelectList(getDateTypes(), string.Empty);
            return PartialView("iConsumptionPeriod");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpireFilter]
        public ActionResult AddConsumptionPeriod(PRISM.TBL_CONSUMPTION_PERIOD p, FormCollection val)
        {
            int entrybyid = int.Parse(User.Identity.Name.ToString());
            //p.FK_ItemId = new Guid(val["ConsumptionItem"]);
            //p.ConsumptionTime = val["TimeFrams"];
            p.PK_DATEID = Guid.NewGuid().ToString();
            p.ENTRYBY = entrybyid;
            p.ENTRYTIME = DateTime.Now.Date;
            try
            {
                db.TBL_CONSUMPTION_PERIOD.Add(p);
                db.SaveChanges();
                return RedirectToAction("Index");

            }
            catch (Exception e)
            {
                var ex = e;
                return View();
            }

        }

        [SessionExpireFilter]
        public ActionResult ViewConsumption()
        {
            var dat = new SettingsDbHelper();
            var data = dat.GetConsumptionPeriodDetail();
            return PartialView("iViewConsumption", data);
        }

        [SessionExpireFilter]
        public ActionResult DetailConsuptionP(string id)
        {
            var cid = new Guid(id);
            //var data = (from xi in db.tbl_ConsumptionPeriod
            //            join xj in db.Assets on new { itemid = xi.FK_ItemId } equals new { itemid = xj.guid }
            //            where xi.PK_DateId == cid
            //            select new
            //            {

            //            });
            var query = (from a in db.TBL_CONSUMPTION_PERIOD
                         join b in db.TBL_ASSET on new { FK_ItemId = a.FK_ITEMID } equals new { FK_ItemId = b.PK_ASSET_ID }
                         where
                           a.PK_DATEID == id
                         select new
                         {
                             a.PK_DATEID,
                             a.FK_ITEMID,
                             a.ALLOWEDQTY,
                             a.CONSUMPTIONPERIOD,
                             a.CONSUMPTIONTIME,
                             a.ENTRYBY,
                             a.ENTRYTIME,
                             a.LASTEDITDATE,
                             b.PK_ASSET_ID,
                             b.BOOKPAGEID,
                             b.ITEMNAME,
                             b.SPECIFICATION,
                             b.FK_UOM_ID,
                             b.ITEM_DESC,
                             b.ITEMCATEGORYCODE,
                             b.ENTRYDATE,
                             Column1 = b.ENTRYBY
                         }
                       ).AsEnumerable().Select(xs => new PRISM.Models.spConsumption
                       {
                           Dateid = xs.PK_DATEID,
                           FK_ASSET_ID = xs.FK_ITEMID,
                           ITEMNAME = xs.ITEMNAME,
                           allowedQty = xs.ALLOWEDQTY.ToString(),
                           consumpPeriod = xs.CONSUMPTIONPERIOD,
                           ConsumpTime = xs.CONSUMPTIONTIME,
                           itemDesc = xs.ITEM_DESC,
                       });
            var data = query.SingleOrDefault();
            ViewBag.TimeFrams = new SelectList(getDateTypes(), string.Empty);
            return PartialView("iDetailConsuptionP", data);
        }

        [SessionExpireFilter]
        public ActionResult UnitOfMeasure()
        {

            return PartialView("iUnitOfMeasure");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionExpireFilter]
        public ActionResult AddUnitOfMeasure(PRISM.TBL_MEASURINGUNITS_MASTER ms)
        {
            ms.PK_UOM_ID = Guid.NewGuid().ToString();
            ms.ENTRYID = int.Parse(User.Identity.Name.ToString());
            ms.CREATEDDATE = DateTime.Now;
            try
            {
                db.TBL_MEASURINGUNITS_MASTER.Add(ms);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {

                var ex = e;
                return View();
            }

        }

        [SessionExpireFilter]
        public ActionResult ViewUnitOfMeasure()
        {
            var dat = new SettingsDbHelper();
            var data = dat.getMeasuringUnitDetail();
            return PartialView("iViewUnitOfMeasure", data);
        }

        public ActionResult EditUnitOfMeasure(string s)
        {
            var qid = new Guid(s);
            var q = db.TBL_MEASURINGUNITS_MASTER.Where(x => x.PK_UOM_ID == s).FirstOrDefault();
            return PartialView("iEditUnitOfMeasure", q);
        }

        public ActionResult EditVendor(string id)
        {
            var qid = new Guid(id);
            var q = db.TBL_VENDOR.Where(x => x.PK_VENDORID == id).FirstOrDefault();
            return PartialView("iEditVendor", q);
        }

PRISM/Views/Settings/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2 class="settings-placeholder">Settings</h2>
<div class="span2">
    <div class="sidebar light">
        @if (Request.IsAuthenticated)
        {
            <ul>
                <li>
                    <a href="#"> Vendor</a>
                    <ul class="dropdown-menu" data-role="dropdown">
                        @Ajax.ActionLink("Vendor Setup", "VendorSetup", new AjaxOptions { UpdateTargetId = "containerid", InsertionMode = InsertionMode.Replace, HttpMethod = "POST", OnComplete="checkSessionTimeout(xhr);" })
                        @Ajax.ActionLink("List Vendor", "ViewVendor", new AjaxOptions { UpdateTargetId = "containerid", InsertionMode = InsertionMode.Replace, HttpMethod = "POST", OnComplete="checkSessionTimeout(xhr);" })
                    </ul>
                </li>
                <li>
                    <a href="#">Consumption Period</a>
                <ul class="dropdown-menu" data-role="dropdown">
                    @Ajax.ActionLink("Consumption Setup", "ConsumptionPeriod", new AjaxOptions { UpdateTargetId = "containerid", InsertionMode = InsertionMode.Replace, HttpMethod = "POST", OnComplete="checkSessionTimeout(xhr);" })
                    @Ajax.ActionLink("List Consumption", "ViewConsumption", new AjaxOptions { UpdateTargetId = "containerid", InsertionMode = InsertionMode.Replace, HttpMethod = "POST" , OnComplete="checkSessionTimeout(xhr);"})
                </ul>
            </li>
                <li>
                <a href="#">Unit Of Measure</a>
                <ul class="dropdown-menu" data-role="dropdown">
                    <li>
                        @Ajax.ActionLink("Uom Setup", "UnitOfMeasure", new AjaxOptions { UpdateTargetId = "containerid", InsertionMode = InsertionMode.Replace, HttpMethod = "POST", OnComplete="checkSessionTimeout(xhr);" })
                        @Ajax.ActionLink("List UoM", "ViewUnitOfMeasure", new AjaxOptions { UpdateTargetId = "containerid", InsertionMode = InsertionMode.Replace, HttpMethod = "POST", OnComplete="checkSessionTimeout(xhr);" })
                    </li>
                </ul>
                </li>

        </ul>
        }
        

    </div>
</div>
<div class="span10 place-left" style="background:#fff;">
    <div id="containerid">

    </div>
</div>
@section userscript{
    <script type="text/javascript" src="~/Scripts/jquery.unobtrusive-ajax.js"></script> 
}

PRISM/Views/Settings/iConsumptionPeriod.cshtml
@model PRISM.TBL_CONSUMPTION_PERIOD
@{
    ViewBag.Title = "iConsumptionPeriod";
}
<script src="@Url.Content("~/Scripts/jquery-1.8.2.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>
<h2>@PRISM.Resource.ConsumptionPeriodSetup</h2>
<div class="grid condensed">
    @using (Html.BeginForm("AddConsumptionPeriod", "settings", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="row cells4">
            <div class="cell labelfor">@PRISM.Resource.ConsumptionPeriodForItem</div>
            <div class="cell ">                
                @*@Html.DropDownList("ConsumptionItem", string.Empty)*@
                @Html.DropDownListFor(model => model.FK_ITEMID, ViewBag.ConsumptionItem as SelectList, @PRISM.Resource.SelectItem)
                @Html.ValidationMessageFor(model => model.FK_ITEMID)
            </div>
            <div class="cell labelfor">@PRISM.Resource.Period</div>
            <div class="cell ">
                @Html.TextBoxFor(model => model.CONSUMPTIONPERIOD, new { type = "number" })
                @Html.ValidationMessageFor(model => model.CONSUMPTIONPERIOD)
            </div>
        </div>
        <div class="row cells4">
            <div class="cell labelfor">@PRISM.Resource.AllowedQuantity</div>
            <div class="cell ">
                @*@Html.EditorFor(xs => Model.VendorName)*@
               @Html.EditorFor(model => model.ALLOWEDQTY, new { type="number"})
                @Html.ValidationMessageFor(model => model.ALLOWEDQTY)
            </div>
            @*<div class="cell labelfor">Duration</div>
            <div class="cell ">
                @Html.DropDownList("TimeFrams", string.Empty)
            </div>*@
        </div>
        <div class="row cells4">
            <div class="cell labelfor">@PRISM.Resource.Duration</div>
            <div class="cell ">
                @*@Html.EditorFor(xs => Model.VendorName)*@
                @Html.DropDownListFor( model=>model.CONSUMPTIONTIME,ViewBag.TimeFrams as SelectList, @PRISM.Resource.SelectTimeSpan)
                @Html.ValidationMessageFor(model => model.CONSUMPTIONTIME)
            </div>
            <div class="cell labelfor"></div>
            <div class="cell ">
               <input type="submit" value="@PRISM.Resource.Create"/>
            </div>
        </div>
    }
</div>

PRISM/Views/Settings/iDetailConsuptionP.cshtml
@model PRISM.Models.spConsumption

@{
    ViewBag.Title = "iDetailConsuptionP";
}

<h2>Edit Consumption Period</h2>
@using (Html.BeginForm("UpdateConsumptionP","Settings",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="grid condensed">
    <div class="row cells4">
        <div class="cell labelfor">@PRISM.Resource.ItemName</div>
        <div class="cell ">
            @Html.TextBoxFor(model => model.ITEMNAME, new { disabled = "disabled" })
        </div>
        <div class="cell labelfor">@PRISM.Resource.AllowedQuantity)</div>
        <div class="cell ">
            @Html.TextBoxFor(model => model.allowedQty)

            @Html.Hidden("hddSerialNo", "")
            @Html.HiddenFor(model => model.Dateid)
            @Html.HiddenFor(model => model.FK_ASSET_ID)
           
        </div>
    </div>
    <div class="row cells4">
        <div class="cell labelfor">@PRISM.Resource.Period</div>
        <div class="cell ">
            @Html.TextBoxFor(model => model.consumpPeriod)
        </div>
        <div class="cell labelfor">@PRISM.Resource.Duration)</div>
        <div class="cell ">
            @*@Html.TextBoxFor(model => model.ConsumpTime)*@
            @Html.DropDownListFor(model => model.ConsumpTime, ViewBag.TimeFrams as SelectList, @PRISM.Resource.SelectTimeSpan)

        </div>
    </div>
    <div class="row cells4">
        <div class="cell labelfor">@PRISM.Resource.Description</div>
        <div class="cell ">
            @Html.TextBoxFor(model => model.itemDesc, new { disabled = "disabled" })
        </div>
        <div class="cell labelfor"></div>
        <div class="cell ">
          <input type="submit" value="@PRISM.Resource.Save" />
            <input type="button" onclick="window.history.back()" value="@PRISM.Resource.CancelButton" class="cancel-button btn-form" />
        </div>
    </div>
</div>

}

PRISM/Views/Settings/iEditUnitOfMeasure.cshtml
@model PRISM.TBL_MEASURINGUNITS_MASTER
@{
    ViewBag.Title = "iEditUnitOfMeasure";
}

<h2>iEditUnitOfMeasure</h2>
@using (Html.BeginForm("updateUnitOfMeasure","Settings",FormMethod.Post))
{
    <div class="grid condensed">
        <div class="row cells4">
            <div class="cell labelfor">
                @PRISM.Resource.Unit :
            </div>
            <div class="cell">
                @Html.DisplayFor(m=>m.UNITNAME)
                @Html.ValidationMessageFor(xs => Model.UNITNAME)
            </div>

        </div>
        <div class="row cells4">
            <div class="cell labelfor">
                
            </div>
            <div class="cell">
                @Html.TextBoxFor(m => m.PK_UOM_ID, new { disabled = "disabled" })
                @Html.HiddenFor(m => m.PK_UOM_ID)
            </div>

        </div>
        <div class="row cells4">
            <div class="cell labelfor">
                @PRISM.Resource.Unit :
            </div>
            <div class="cell">
               @Html.TextBoxFor(m => m.UNITNAME)
                @Html.ValidationMessageFor(xs => Model.UNITNAME)
            </div>

        </div>
        <div class="row cells4">
            <div class="cell labelfor">
                @PRISM.Resource.UnitShort :
            </div>
            <div class="cell">
               @Html.TextBoxFor(m => m.UNITSHORT)
                @Html.ValidationMessageFor(xs => Model.UNITSHORT)
            </div>

        </div>
        <div class="row cells4">
            <div class="cell labelfor">
                @PRISM.Resource.Description :
            </div>
            <div class="cell">
               @Html.TextBoxFor(m => m.DESCRIPTION)
                @Html.ValidationMessageFor(xs => Model.DESCRIPTION)
            </div>

        </div>
        <div class="row cells4">
            <div class="cell labelfor">

            </div>
            <div class="cell">
                <input type="submit" value="Save" />
                <input value="Cancel" onclick="history.go(-1);" type="button" />
            </div>

        </div>
    </div>
    
}

PRISM/Views/Settings/iEditVendor.cshtml
@model PRISM.TBL_VENDOR

@using (Html.BeginForm("updateVendor", "Settings", FormMethod.Post))
{
    <div class="grid condensed">
        <div class="row cells4">
            <div class="cell labelfor">

            </div>
            <div class="cell">
                @Html.TextBoxFor(m => m.PK_VENDORID, new { disabled = "disabled" })
                @Html.HiddenFor(m => m.PK_VENDORID)
            </div>
            <div class="cell labelfor">
                @PRISM.Resource.VendorName
            </div>
            <div class="cell">
                @Html.TextBoxFor(m => m.VENDORNAME)
                @Html.ValidationMessageFor(xs => Model.VENDORNAME)

            </div>

        </div>
        <div class="row cells4">
            <div class="cell labelfor">
                @PRISM.Resource.Address
            </div>
            <div class="cell">
                @Html.TextBoxFor(m => m.ADDRESS)
                @Html.ValidationMessageFor(xs => Model.ADDRESS)

            </div>
            <div class="cell labelfor">
                @PRISM.Resource.Address2
            </div>
            <div class="cell">
                @Html.TextBoxFor(m => m.ADDRESS2)

            </div>

        </div><div class="row cells4">
            <div class="cell labelfor">
                @PRISM.Resource.ContactPerson
            </div>
            <div class="cell">
                @Html.TextBoxFor(m => m.CONTACTPERSON)
                @Html.ValidationMessageFor(xs => Model.CONTACTPERSON)

            </div>
            <div class="cell labelfor">
                @PRISM.Resource.Phone
            </div>
            <div class="cell">
                @Html.TextBoxFor(m => m.PHONENO)
                @Html.ValidationMessageFor(xs => Model.PHONENO)

            </div>

        </div><div class="row cells4">
            <div class="cell labelfor">
                @PRISM.Resource.Phone1
            </div>
            <div class="cell">
                @Html.TextBoxFor(m => m.PHONENO1)

            </div>
            <div class="cell labelfor">
                @PRISM.Resource.Email
            </div>
            <div class="cell">
                @Html.TextBoxFor(m => m.EMAIL)

            </div>

        </div><div class="row cells4">
            <div class="cell labelfor">
                @PRISM.Resource.Fax
            </div>
            <div class="cell">
                @Html.TextBoxFor(m => m.FAXNO)

            </div>
            <div class="cell labelfor">
                @PRISM.Resource.Terretory
            </div>
            <div class="cell">
                @Html.TextBoxFor(m => m.TERRETORY)
                @Html.ValidationMessageFor(xs => Model.TERRETORY)

            </div>

        </div><div class="row cells4">
            <div class="cell labelfor">
                @PRISM.Resource.Country
            </div>
            <div class="cell">
                @Html.TextBoxFor(m => m.COUNTRY)
                @Html.ValidationMessageFor(xs => Model.COUNTRY)

            </div>
            <div class="cell labelfor">
                @PRISM.Resource.CurrencyCode
            </div>
            <div class="cell">
                @Html.TextBoxFor(m => m.CURRENCYCODE)
                @Html.ValidationMessageFor(xs => Model.CURRENCYCODE)

            </div>

        </div><div class="row cells4">
            <div class="cell labelfor">
                @PRISM.Resource.Status
            </div>
            <div class="cell">
                @Html.TextBoxFor(m => m.BLOCKED)

            </div>
            <div class="cell labelfor">
                @PRISM.Resource.VatRegNum
            </div>
            <div class="cell">
                @Html.TextBoxFor(m => m.VATREGNO)
                @Html.ValidationMessageFor(xs => Model.VATREGNO)
            </div>

        </div><div class="row cells4">
            <div class="cell labelfor">

            </div>
            <div class="cell">

            </div>
            <div class="cell labelfor">

            </div>
            <div class="cell">
                <input type="submit" value="Save" />
                <input value="Cancel" onclick="history.go(-1);" type="button"/>
            </div>

        </div>

    </div>
}

PRISM/Views/Settings/iPaybook.cshtml
@{
    ViewBag.Title = "iPaybook";
}

<h2>iPaybook</h2>

PRISM/Views/Settings/iUnitOfMeasure.cshtml
@model PRISM.TBL_MEASURINGUNITS_MASTER
@{
    ViewBag.Title = "iUnitOfMeasure";
}
<script src="@Url.Content("~/Scripts/jquery-1.8.2.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>
<h2>@PRISM.Resource.UnitOfMeasure</h2>

<div class="grid condensed">
    @using (Html.BeginForm("AddUnitOfMeasure", "Settings", FormMethod.Post))
    { @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
      <div class="row cells4">
        <div class="cell labelfor">@PRISM.Resource.Unit</div>
        <div class="cell ">
            @Html.EditorFor(xs=>Model.UNITNAME)
            @Html.ValidationMessageFor(xs => Model.UNITNAME)
        </div>
        <div class="cell labelfor">@PRISM.Resource.UnitShort</div>
        <div class="cell ">
            @Html.EditorFor(xs => Model.UNITSHORT)
            @Html.ValidationMessageFor(xs => Model.UNITSHORT)
        </div>
    </div>
        <div class="row cells4">
        <div class="cell labelfor">@PRISM.Resource.Description</div>
        <div class="cell ">
            @Html.EditorFor(xs=>Model.DESCRIPTION)
            @Html.ValidationMessageFor(xs => Model.DESCRIPTION)
        </div>
        <div class="cell labelfor"></div>
        <div class="cell ">
           <input type="submit" value="@PRISM.Resource.Create" />
        </div>
    </div>
    }
    </div>

PRISM/Views/Settings/iVendorDetail.cshtml
@model PRISM.Models.spVendor
@{
    ViewBag.Title = "iVendorDetail";
}

<h2>Vendor Detail</h2>
<h2>
    <strong>@Html.DisplayFor(model => model.VendorName)</strong>
</h2>
<!--Line Data-->
<div class="grid condensed">
    <div class="row cells4">
        <div class="cell labelfor">Address</div>
        <div class="cell ">
            @Html.DisplayFor(model => model.Address)
        </div>
        <div class="cell labelfor">Address 2</div>
        <div class="cell ">
            @Html.DisplayFor(model => model.Address2)
        </div>
    </div>
    <div class="row cells4">
        <div class="cell labelfor">Contact Person</div>
        <div class="cell ">
            @Html.DisplayFor(model => model.ContactPerson)
        </div>
        <div class="cell labelfor">Phone No</div>
        <div class="cell ">
            @Html.DisplayFor(model => model.PhoneNo);
        </div>
    </div>
    <div class="row cells4">
        <div class="cell labelfor">Phone No2</div>
        <div class="cell ">
            @Html.DisplayFor(model => model.PhoneNo1);
        </div>
        <div class="cell labelfor">Email</div>
        <div class="cell ">
            @Html.DisplayFor(e => e.Email)
        </div>
    </div>
    <div class="row cells4">

        <div class="cell labelfor">Fax NO</div>
        <div class="cell ">
            @Html.DisplayFor(model => model.FaxNo)
        </div>
        <div class="cell labelfor">Terretory</div>
        <div class="cell ">
            @Html.DisplayFor(model => model.Terretory)
        </div>
    </div>
    <div class="row cells4">
        <div class="cell labelfor">Country</div>
        <div class="cell ">
            @Html.DisplayFor(model => model.Country)
        </div>

        <div class="cell labelfor">Currency Code</div>
        <div class="cell ">
            @Html.DisplayFor(e => e.CurrencyCod)
        </div>
    </div>
    <div class="row cells4">
        <div class="cell labelfor">VAT reg no</div>
        <div class="cell ">
            @Html.DisplayFor(model => model.VatRegistrationNo)
        </div>
        <div class="cell labelfor">Active</div>
        <div class="cell ">
            @Html.DisplayFor(e => e.isActice)
        </div>
    </div>
    

</div>